services:
  - type: web
    name: local-service-booking-frontend
    runtime: static
    rootDir: frontend/local-service-booking
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://local-service-booking-fm3u.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
